name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install uv
        run: pip install uv

      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: 3.x

      - name: Sync environment
        run: task sync

      - name: Run linter
        run: task lint

      - name: Run tests
        run: task test
